### ISSUE TITLE
two issues

### ISSUE THREAD

**Issue by bedle88** [learn-co-curriculum/diy-json-serializer-ruby#14]
I had two issues with this readme as it's written. First, my api was giving me a string rather than json so I had to change each .get ajax request to .getJSON (even though I was rendering as JSON). Second, I think the show.html.erb page is missing an event.preventDefault so that the page doesn't refresh when you press next.

**Comment by itzsaga** [comment]
Yeah, `.getJSON` would be nice to see in the example. This was taken care of in PR #7 but never merged.

**Comment by gj** [comment]
Merged in #7. Thanks @bedle88 and @itzsaga !

Regarding your second concern @bedle88, would you mind providing a little more detail? Also happy to look at a PR if you want to make the change yourself. 🙂

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
