### ISSUE TITLE
get vs getJSON in readme

### ISSUE THREAD

**Issue by lawrend** [learn-co-curriculum/diy-json-serializer-ruby#18]
In lines 258-274 of the readme we modify the posts/index view to display the remainder of the description when we press the "More" button. The text says that if we don't change "get" to "getJSON" then it will return as undefined. Without our hand-built serializer that would be true (I think), but in this case it renders correctly.

**Comment by drakeltheryuujin** [comment]
Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

Thanks for contributing! 💙
