### ISSUE TITLE
$.getJSON

### ISSUE THREAD

**Issue by Ary770** [learn-co-curriculum/diy-json-serializer-ruby#20]
>  But first, we have to tell jQuery to expect to receive JSON data by calling $.getJSON() instead of $.get(). Otherwise, jQuery will treat data as a string, and data["description"] will return undefined.

I tried this on my browser but it didn't make a difference if I used $.get or $.getJSON. In both cases, I was able to see the description...

**Comment by drakeltheryuujin** [comment]
Thank you for your feedback! We're revamping our materials and we'll take this information into consideration in upcoming releases of this curriculum.

Thanks for contributing! 💙
