### ISSUE TITLE
$.get() vs $.getJSON()

### ISSUE THREAD

**Issue by cboujoukos** [learn-co-curriculum/diy-json-serializer-ruby#21]
This statement is no longer true:

As you can see, we can access the JSON just like any other dictionary, and get the value for the "description" key. But first, we have to tell jQuery to expect to receive JSON data by calling $.getJSON() instead of $.get(). Otherwise, jQuery will treat data as a string, and data["description"] will return undefined

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
