### ISSUE TITLE
Code along solution does not work for show.html.erb without passing in the event and preventing the default action. 

### ISSUE THREAD

**Issue by emikojima** [learn-co-curriculum/diy-json-serializer-ruby#22]
The code along solution is missing 
$(function () {
  $(".js-next").on("click", function(**e**) {
    **e.preventDefault()**
in the show.html.erb

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
