### ISSUE TITLE
Next Post button handling issues

### ISSUE THREAD

**Issue by BarbaraPruz** [learn-co-curriculum/diy-json-serializer-ruby#23]
For this code to work, the event handler needs to also call preventDefault() or return false

Also,  after getting the next post and updating the content, the url still shows the original post id.   I think it can be fixed by doing something like pushing new url onto browser history.   If code sample isn't going to address this inconsistency (since it might distract from the JSON and AJAX discussion), it seems that at least a note should be added to the  lesson so people are aware (and know this isn't ideal sample code to directly re-use in other situations)

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
