### ISSUE TITLE
The tests included in this lab do not relate to what is worked on

### ISSUE THREAD

**Issue by mseaman6** [learn-co-curriculum/diy-json-serializer-ruby#24]
This would be fine if they were already passing, but they are not.  Additionally, you have to make a lot of changes to either the specs or the app to get them to pass (as can be seen by the issues already submitted), since the tests and the existing code do not seem to correspond to each other (i.e. as it exists there are posts and associated authors, but the tests do not deal with authors, and have an additional "name" field for the post, etc.).  

Especially since this is a code-along, this could be fixed by simply removing the tests (and would be a lot less frustrating to the students).

**Comment by mseaman6** [comment]
My issue is actually for https://github.com/learn-co-students/diy-json-serializer-ruby-v-000.  On the  lesson found here (https://learn.co/tracks/full-stack-web-development-v6/rails-and-javascript/building-apis/diy-json-serializer#) the github button links to the above repo, but the raise an issue button on the same page goes to this repo.

**Comment by Peter-G-Stone** [comment]
just dropping in to say the tests seem to still be unrelated to the code-along --- fyi

**Comment by SilverBright** [comment]
Just letting everyone know there's still a problem with the tests.  I've commented them all out in order to pass and move to the lab.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
