### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by AlexFriedland** [learn-co-curriculum/diy-json-serializer-ruby#25]
the JS doesn't work as advertised. the .getJSON call doesn't append anything as it's set up in the codealong. 

Also, the spec file is set up to instantiate an object that throws an error before it even runs a test.  It's testing for post.author.name on the show page, but the object itself is instantiated with a name.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
