### ISSUE TITLE
suggested test revisions

### ISSUE THREAD

**Issue by justinddaniel** [learn-co-curriculum/diy-json-serializer-ruby#26]
# features/post_spec.rb

require 'rails_helper'

describe 'navigate' do
  before do
    @post = Post.create(title: "My Post", description: "My post desc") # name is not a column of table 
    posts
   author = Author.create(name: "Steven") 
   @post.author = author 
   author.posts << @post
   author.save 
   @post.save 
end

  it 'shows the title on the show page in a h1 tag' do
    visit post_path(@post)
    expect(page).to have_css("h1", text: "My Post")
  end

  it 'to post pages' do
    visit post_path(@post)
    expect(page.status_code).to eq(200)
  end

  it 'shows the description on the show page in a p tag' do
    visit post_path(@post)
    expect(page).to have_css("p", text: "My post desc")
  end
end

describe 'form' do
  it 'shows a new form that submits content and redirects and prints out params' do
    visit new_post_path

    fill_in 'title', with: "My post title"
    fill_in 'description', with: "My post description"

    click_on "Submit Post"

    expect(page).to have_content("My post title")
  end

  it 'shows a new form that submits content and redirects and prints out params' do
    @post = Post.create(title: "My Post", description: "My post desc")

    visit edit_post_path(@post)

    fill_in 'post[title]', with: "My edit"
    fill_in 'post[description]', with: "My post description"

    click_on "Submit Post"  # students are using the same partial for both edit and new, so button remains same

    expect(page).to have_content("My edit")
  end
end

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
