### ISSUE TITLE
Issues with code examples and tests

### ISSUE THREAD

**Issue by arianaberger** [learn-co-curriculum/diy-json-serializer-ruby#28]
1. Using JSON To Build The Show Page: Code is missing a preventDefault() so that the JS doesn't work properly in the browser. JS ode for show page should be this:

```
<script type="text/javascript" charset="utf-8">
$(function () {
  $(".js-next").on("click", function(e) {
  	e.preventDefault();
    var nextId = parseInt($(".js-next").attr("data-id")) + 1;
    $.getJSON("/posts/" + nextId + "/post_data", function(data) {
      $(".postTitle").text(data["title"]);
      $(".postBody").text(data["description"]);
      // re-set the id to current on the link
      $(".js-next").attr("data-id", data["id"]);
    });
  });
});
</script>
```

2. Tests have a multitude of issues with Capybara and the form partial. None of the tests were passing initially. Edited some of the tests to fix the Capybara issue and also updated the submit button:

```
  <div class="actions">
    <%= f.submit @post.id ? "Update Post" : "Submit Post" %>
</div>
```

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
