### ISSUE TITLE
Issues with get vs getJSON and post.author.name

### ISSUE THREAD

**Issue by yinazee** [learn-co-curriculum/diy-json-serializer-ruby#29]
errors were raised even though correct attributes were provided in readme

-there were many errors that were not related to the lab. such as the submit form

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
