### ISSUE TITLE
Bug fixes for the lesson.

### ISSUE THREAD

**Issue by Emanao** [learn-co-curriculum/diy-json-serializer-ruby#30]
CODE:
To prevent the anchor tag from opening the link(default behavior), I added the JQuery method preventDefault. 
Returning false from jQuery event handlers is equivalent to calling both, e.preventDefault and e.stopPropagation. So it also works.
TEST SPEC:
I commented the whole test spec since it is a code-along lesson.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
