### ISSUE TITLE
Echoing Continued problems with the Test

### ISSUE THREAD

**Issue by aburk3** [learn-co-curriculum/diy-json-serializer-ruby#31]
Followed the code along point by point. 

"If we reload and go to our first post, then click Next, we get that smooth AJAX data refresh we've been looking for." 

I didn't get smooth AJAX, I didn't get anything really except for a flash of the new post on the screen. 

Not only that, but there are tests that are not related to the codealong - "This is a code-along. Manually fork and clone the repository on GitHub to follow along." Even with the failed AJAX call, there are other required tests that were not mentioned in the codealong. Is this supposed to be a Lab?

**Comment by gac2117** [comment]
#28  This helped me fix that error you got

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
