### ISSUE TITLE
The lab is still not fixed???

### ISSUE THREAD

**Issue by Jcg408** [learn-co-curriculum/diy-json-serializer-ruby#32]
Very frustrating - this is a codealong. We follow along exactly and we get errors which have nothing to do with this part of the learning so the tests don't pass. Also issues with the JSON code. I noticed in many of the labs in the Javascript/Rails section there are mistakes, omissions, poorly written instructions. Please fix this or delete the labs!

**Comment by gnappo1** [comment]
To have an updated version of the tests, copy/paste the tests from my pull request here:
https://github.com/learn-co-students/diy-json-serializer-ruby-v-000/pull/367

The pull request is pending approval, hopefully, it will get fixed soon!

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
