### ISSUE TITLE
Goes too far, too fast

### ISSUE THREAD

**Issue by JeffKatzy** [learn-co-curriculum/diy-json-serializer-ruby#5]
I wouldn't start off with a separate serializer object.  Instead, I would just talk about sending back json in general from the controller.  And sending information back that way.

Then talk about a json representation of an object, and how we may need to modify that.

And then talk about the need for a separate object, which is like a view object - ie, bring in separation of concerns, and a discussion about where we should place this logic.

**Comment by JeffKatzy** [comment]
Also, no need to do string concatenation.  Just return a hash.  And manipulate a hash.

**Comment by JeffKatzy** [comment]
Might stay away from the word 'cast', and use hash instead of dictionary.

**Comment by drakeltheryuujin** [comment]
Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

Thanks for contributing! 💙
